### ISSUE TITLE
"live" app

### ISSUE THREAD

**Issue by ThomasWaldmann** [ThomasWaldmann/pretalx#10]
pretalx was made for the "pre-talks" phase (e.g. cfp, schedule making) and not for running a "live" event.

Considering that, I am thinking whether we should add a "live" python package (== "live" django app) inside pretalx for better separation and also to have a kind of minimal, clean place to start our stuff.

It could be rooted at `/<eventname>/live`.

**Comment by ThomasWaldmann** [comment]
I try to work on this.

But if some more productive django developer wants to grab this, don't let that hold you back and add a comment below!

**Comment by twgaras** [comment]
You self-assigned, so I am assuming you are working on it?
Do you need help with it?

**Comment by ThomasWaldmann** [comment]
I'll make a PR soon, so you can review it.
